### ISSUE TITLE
run time error

### ISSUE THREAD

**Issue by lakerzhou-lenovo** [cetic/tsimulus-cli#1]
I compiled from source, but got exception when run the code. Can anyone help me? thanks.
root@04f26eb2ee71:~/tsimulus-cli# sbt run demo1.json
[info] Loading project definition from /root/tsimulus-cli/project
[info] Set current project to tsimulus-cli (in build file:/root/tsimulus-cli/)
[info] Running be.cetic.tsimulus.cli.Main
[error] (run-main-0) java.lang.ArrayIndexOutOfBoundsException: 0
java.lang.ArrayIndexOutOfBoundsException: 0
        at be.cetic.tsimulus.cli.Main$.main(Main.scala:16)
        at be.cetic.tsimulus.cli.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 1 s, completed Oct 3, 2017 10:36:38 PM

**Comment by mgoeminne** [comment]
Hello, thank you for your bug report. I'll try to fix it very soon (should take a couple of days).

**Comment by alexnuttinck** [comment]
You need to run the code with a single command of sbt with only one argument: 
```
sbt "run demo1.json"

**Comment by lakerzhou-lenovo** [comment]
Thanks Mathieu for the fix.
