### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by StephenOTT** [cetic/tsimulus-cli#4]
```
java -jar rts-gen-console.jar fakedata.json
Exception in thread "main" java.lang.ExceptionInInitializerError
	at be.cetic.rtsgen.console.Main$.main(Main.scala:22)
	at be.cetic.rtsgen.console.Main.main(Main.scala)
Caused by: java.io.FileNotFoundException: /Users/mg/Documents/IDEA projects/time-series-generator/target/scala-2.11/scoverage-data/scoverage.measurements.1 (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileWriter.<init>(FileWriter.java:107)
	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
	at scoverage.Invoker$.invoked(Invoker.scala:42)
	at be.cetic.rtsgen.generators.TimeToJson$class.$init$(TimeToJson.scala:26)
	at be.cetic.rtsgen.config.Configuration$.<init>(Configuration.scala:72)
	at be.cetic.rtsgen.config.Configuration$.<clinit>(Configuration.scala)
	... 2 more
```

**Comment by LibertyWalk** [comment]
I'm facing the same problem. Any updates on this?

**Comment by StephenOTT** [comment]
@LibertyWalk my fallback was to the use https://github.com/cetic/tsimulus-ms

**Comment by jumaka** [comment]
I ended up using the workaround too - I get the same error. OpenJDK 10

**Comment by mgoeminne** [comment]
Could you please confirm this problem is fixed with [tsimulus-cli v1.1](https://github.com/cetic/tsimulus-cli/releases/tag/v1.1)? Thank you.

**Comment by mgoeminne** [comment]
No answer, I close this issue. Feel free to reopen it if the issue remains.

**Comment by jumaka** [comment]
I can confirm that this now works in 1.1 and 1.16. Thanks Justin
